PROVINCIA_TO_SUBDIV = {
    "Albacete": "CM",
    "Alicante": "VC",
    "Almería": "AN",
    "Álava": "PV",
    "Asturias": "AS",
    "Ávila": "CL",
    "Badajoz": "EX",
    "Barcelona": "CT",
    "Bizkaia": "PV",
    "Burgos": "CL",
    "Cáceres": "EX",
    "Cádiz": "AN",
    "Cantabria": "CB",
    "Castellón": "VC",
    "Ciudad Real": "CM",
    "Córdoba": "AN",
    "Cuenca": "CM",
    "Gipuzkoa": "PV",
    "Girona": "CT",
    "Granada": "AN",
    "Guadalajara": "CM",
    "Huelva": "AN",
    "Huesca": "AR",
    "Illes Balears": "IB",
    "Jaén": "AN",
    "La Rioja": "RI",
    "Las Palmas": "CN",
    "León": "CL",
    "Lleida": "CT",
    "Lugo": "GA",
    "Madrid": "MD",
    "Málaga": "AN",
    "Murcia": "MC",
    "Navarra": "NC",
    "Ourense": "GA",
    "Palencia": "CL",
    "Pontevedra": "GA",
    "Salamanca": "CL",
    "Santa Cruz de Tenerife": "CN",
    "Segovia": "CL",
    "Sevilla": "AN",
    "Soria": "CL",
    "Tarragona": "CT",
    "Teruel": "AR",
    "Toledo": "CM",
    "Valencia": "VC",
    "Valladolid": "CL",
    "Zamora": "CL",
    "Zaragoza": "AR"
}